apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:      
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        startupProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          failureThreshold: 20
          periodSeconds: 5
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
