# Obrigo meus pods nginx-aaa rodarem em nodes diferentes.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-aaa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-aaa
  template:
    metadata:
      labels:
        app: nginx-aaa
    spec:
      containers:
      - name: nginx-aaa
        image: nginx
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - "nginx-aaa" # Obrigo meus pods nginx-aaa rodarem em nodes diferentes.
              topologyKey: kubernetes.io/hostname # Uma label que exista nos nodes.
