apiVersion: v1
kind: Namespace
metadata:
    name: homolog  
      
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: homolog
spec:
  selector:
    app: api # Label do Deployment
  ports:
  - port: 8080
    targetPort: 80
  type: NodePort