apiVersion: v1
kind: Namespace
metadata:
    name: homolog

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: homolog
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP