apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: meuprimeiro-replicaset
spec:
    selector:
        matchLabels:
          app: exemplo
    template:
        metadata:
          labels:
              app: exemplo
        spec:
            containers:
                - name: meucontainer
                  image: kubedevio/nginx-color:green