apiVersion: v1
kind: Pod
metadata:
  name: meuprimeiropod
  labels:
    name: myapp
spec:
  containers:
  - name: meuprimeiropod
    image: kubedevio/nginx-color:blue
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80