apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-mysql:ubuntu-4.0-latest
      #  resources:
      #    limits:
      #      memory: "512Mi"
      #      cpu: "300m"
        ports:
        - containerPort: 10051
          name: http
          protocol: TCP
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_SERVER_HOST
          value: "mysql.default.svc.cluster.local"
        - name: MYSQL_USER
          value: "zabbix-user"
        - name: MYSQL_PASSWORD
          value: "zabbixpwd"
        - name: MYSQL_DATABASE
          value: "zabbix"