apiVersion: v1
kind: Namespace
metadata:
    name: zabbix-server  
      
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  namespace: default
spec:
  selector:
    app: zabbix-server # Label do Deployment
  ports:
  - port: 10051
    targetPort: 10051
    protocol: TCP
  type: NodePort