apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        resources: {}
        #  limits:
        #    memory: "256Mi"
        #    cpu: "200m"
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_USER
            value: zabbix-user
          - name: MYSQL_PASSWORD
            value: zabbixpwd
          - name: MYSQL_DATABASE
            value: zabbix
          - name: MYSQL_ROOT_PASSWORD
            value: zabbixpwd